interval = 300
splay = 30
splay_first_run = 0
run_lock_timeout = 300
log_level = "warn"
env_path_prefix = "/sbin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin"
ssl_verify_mode = ":verify_none"

[automate]
enable = false
server_url = "https://example.a2server.com"
token = "example_token"
